"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import type { AnalyticsDashboardData, ChartPoint, DashboardCard } from "@/lib/analytics/dashboard";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const palette = ["#0d9488", "#2563eb", "#8b5cf6", "#f59e0b", "#e11d48", "#14b8a6", "#64748b"];
const formatValue = (value: number, monetary = false) => monetary ? money.format(value) : new Intl.NumberFormat("en-US").format(value);

function Drilldown({ href, children }: { href?: string; children: React.ReactNode }) { return href ? <Link href={href}>{children}</Link> : <>{children}</>; }

export function DashboardFilters({ data }: { data: AnalyticsDashboardData }) {
  const router = useRouter(); const [range, setRange] = useState(data.filters.range);
  const submit = (form: HTMLFormElement) => { const values = new FormData(form); const query = new URLSearchParams(); values.forEach((value, key) => { if (typeof value === "string" && value) query.set(key, value); }); router.push(`/c/tidemark-va/dashboard${query.size ? `?${query}` : ""}`); };
  const select = (name: string, label: string, options: Array<{ id: string; label: string }>, selected: string) => <label className="dashboard-filter">{label}<select name={name} defaultValue={selected}><option value="">All</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label>;
  return <form className="dashboard-filters" onSubmit={(event) => { event.preventDefault(); submit(event.currentTarget); }}><label className="dashboard-filter">Period<select name="range" value={range} onChange={(event) => setRange(event.target.value)}><option value="today">Today</option><option value="week">This week</option><option value="month">This month</option><option value="30d">Last 30 days</option><option value="quarter">This quarter</option><option value="ytd">Year to date</option><option value="custom">Custom range</option></select></label>{range === "custom" && <><label className="dashboard-filter">From<input name="from" type="date" defaultValue={data.filters.from}/></label><label className="dashboard-filter">To<input name="to" type="date" defaultValue={data.filters.to}/></label></>}{select("workspace", "Workspace", data.filterOptions.workspaces, data.filters.workspaceId)}{select("client", "Client", data.filterOptions.clients, data.filters.clientId)}{select("provider", "Provider", data.filterOptions.providers, data.filters.providerId)}{select("clinician", "Clinician", data.filterOptions.clinicians, data.filters.clinicianId)}<label className="dashboard-filter">Client status<select name="status" defaultValue={data.filters.status}><option value="">All</option>{data.filterOptions.statuses.map((status) => <option key={status} value={status}>{status}</option>)}</select></label><button className="btn" type="submit">Apply</button><button className="dashboard-refresh" type="button" onClick={() => router.refresh()}>Refresh</button></form>;
}

function KpiCard({ card }: { card: DashboardCard }) { return <Drilldown href={card.href}><section className={`kpi-card ${card.tone ? `kpi-${card.tone}` : ""}`}><span>{card.label}</span><strong>{card.value}</strong>{card.detail && <small>{card.detail}</small>}{card.href && <small className="kpi-link">View details →</small>}</section></Drilldown>; }

function DonutChart({ title, points, monetary = false }: { title: string; points: ChartPoint[]; monetary?: boolean }) {
  const [hovered, setHovered] = useState<string | null>(null); const total = points.reduce((sum, point) => sum + point.value, 0); const segments = points.map((point, index) => ({ point, index, percent: point.value / total * 100, offset: points.slice(0, index).reduce((sum, previous) => sum + previous.value / total * 100, 0) }));
  if (!points.length || !total) return <section className="chart-card"><h2>{title}</h2><p className="muted">No authorized records for this view.</p></section>;
  return <section className="chart-card"><div className="chart-heading"><h2>{title}</h2><span>{formatValue(total, monetary)}</span></div><div className="donut-layout"><svg viewBox="0 0 42 42" className="donut" role="img" aria-label={`${title}: ${points.map((point) => `${point.label} ${formatValue(point.value, monetary)}`).join(", ")}`}><circle cx="21" cy="21" r="15.915" fill="transparent" stroke="#e2e8f0" strokeWidth="5"/>{segments.map(({ point, index, percent, offset }) => { const dash = `${percent} ${100 - percent}`; const element = <circle key={point.label} cx="21" cy="21" r="15.915" fill="transparent" stroke={palette[index % palette.length]} strokeWidth="5" strokeDasharray={dash} strokeDashoffset={-offset} transform="rotate(-90 21 21)" className={hovered && hovered !== point.label ? "chart-faded" : ""} onMouseEnter={() => setHovered(point.label)} onMouseLeave={() => setHovered(null)}/>; return point.href ? <a href={point.href} key={point.label}>{element}</a> : element; })}<text x="21" y="20" textAnchor="middle" className="donut-total">{points.length}</text><text x="21" y="24" textAnchor="middle" className="donut-caption">groups</text></svg><div className="legend">{points.map((point, index) => <Drilldown href={point.href} key={point.label}><button className={`legend-row ${hovered && hovered !== point.label ? "chart-faded" : ""}`} onMouseEnter={() => setHovered(point.label)} onMouseLeave={() => setHovered(null)}><i style={{ backgroundColor: palette[index % palette.length] }}/><span>{point.label}</span><strong>{formatValue(point.value, monetary)}</strong></button></Drilldown>)}</div></div></section>;
}

function BarChart({ title, points, monetary = false }: { title: string; points: ChartPoint[]; monetary?: boolean }) {
  const [hovered, setHovered] = useState<string | null>(null); const max = Math.max(...points.map((point) => point.value), 0);
  if (!points.length || !max) return <section className="chart-card"><h2>{title}</h2><p className="muted">No authorized records for this view.</p></section>;
  return <section className="chart-card"><div className="chart-heading"><h2>{title}</h2><span>{formatValue(points.reduce((sum, point) => sum + point.value, 0), monetary)}</span></div><div className="bar-list">{points.map((point, index) => <Drilldown href={point.href} key={point.label}><div className={`bar-row ${hovered && hovered !== point.label ? "chart-faded" : ""}`} onMouseEnter={() => setHovered(point.label)} onMouseLeave={() => setHovered(null)}><span>{point.label}</span><div className="bar-track"><i style={{ width: `${Math.max(3, point.value / max * 100)}%`, backgroundColor: palette[index % palette.length] }}/></div><strong>{formatValue(point.value, monetary)}</strong></div></Drilldown>)}</div></section>;
}

function TrendChart({ title, points, monetary = false }: { title: string; points: ChartPoint[]; monetary?: boolean }) {
  const [hovered, setHovered] = useState<number | null>(null); const max = Math.max(...points.map((point) => point.value), 1); const plotted = useMemo(() => points.map((point, index) => ({ ...point, x: points.length === 1 ? 50 : index / (points.length - 1) * 100, y: 86 - point.value / max * 70 })), [max, points]);
  if (!points.length) return <section className="chart-card"><h2>{title}</h2><p className="muted">No authorized records for this reporting period.</p></section>;
  return <section className="chart-card"><div className="chart-heading"><h2>{title}</h2><span>{formatValue(points.reduce((sum, point) => sum + point.value, 0), monetary)}</span></div><svg className="trend" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label={`${title}: ${points.map((point) => `${point.label} ${formatValue(point.value, monetary)}`).join(", ")}`}><line x1="0" y1="86" x2="100" y2="86" className="trend-axis"/><polyline points={plotted.map((point) => `${point.x},${point.y}`).join(" ")} fill="none" stroke="#0d9488" strokeWidth="2" vectorEffect="non-scaling-stroke"/>{plotted.map((point, index) => <g key={point.label}><circle cx={point.x} cy={point.y} r="2.1" fill="#0d9488" onMouseEnter={() => setHovered(index)} onMouseLeave={() => setHovered(null)}/>{hovered === index && <><rect x={Math.min(70, Math.max(0, point.x - 14))} y={Math.max(2, point.y - 17)} width="29" height="13" rx="2" fill="#102a43"/><text x={Math.min(84, Math.max(14, point.x))} y={Math.max(10, point.y - 9)} textAnchor="middle" className="trend-tooltip">{formatValue(point.value, monetary)}</text></>}</g>)}</svg><div className="trend-labels">{points.map((point) => <span key={point.label}>{point.label}</span>)}</div></section>;
}

export function AnalyticsDashboard({ data }: { data: AnalyticsDashboardData }) {
  const { charts } = data;
  return <><section className="kpi-grid">{data.cards.map((card) => <KpiCard key={card.label} card={card}/>)}</section><section className="dashboard-chart-grid triple">{charts.clientStatus && <DonutChart title="Client status" points={charts.clientStatus}/>} {charts.arAging && <BarChart title="Accounts receivable aging" points={charts.arAging} monetary/>} {charts.credentialHealth && <BarChart title="Credential health" points={charts.credentialHealth}/>}</section><section className="dashboard-chart-grid triple">{charts.taskStatus && <DonutChart title="Task status" points={charts.taskStatus}/>} {charts.invoiceStatus && <DonutChart title="Invoice status" points={charts.invoiceStatus}/>} {charts.taskPriority && <BarChart title="Task priority" points={charts.taskPriority}/>}</section><section className="dashboard-chart-grid double">{charts.billingTrend && <TrendChart title="Billing trend" points={charts.billingTrend} monetary/>} {charts.collectionsTrend && <TrendChart title="Collections trend" points={charts.collectionsTrend} monetary/>}</section><section className="dashboard-chart-grid double">{charts.clientGrowth && <TrendChart title="Client growth" points={charts.clientGrowth}/>} {charts.workload && <BarChart title="Provider / clinician workload" points={charts.workload}/>}</section>{data.automation && <section className="automation-health"><div><h2>Automation health</h2><p className="muted">Real run, action, AI, and communication queue status.</p></div><div className="health-grid"><span><strong>{data.automation.successfulRuns}</strong>Succeeded runs</span><span><strong>{data.automation.pendingActions}</strong>Pending actions</span><span><strong>{data.automation.aiRequests}</strong>AI requests</span><span><strong>{data.automation.aiFailed}</strong>Failed AI requests</span><span><strong>{data.automation.communicationsFailed}</strong>Failed communications</span></div></section>}<section className="attention-card"><div><h2>Attention required</h2><p className="muted">Operational conditions needing timely action.</p></div>{data.attention.length ? <div className="attention-grid">{data.attention.map((card) => <KpiCard key={card.label} card={card}/>)}</div> : <p className="muted">No authorized overdue, blocked, or expired items require attention.</p>}</section>{data.unavailable.length > 0 && <p className="muted dashboard-unavailable">Some metrics are unavailable because the current role cannot read: {data.unavailable.join(", ")}.</p>}<section className="dashboard-note"><strong>Not shown:</strong> documents requiring attention has no actionable-state field. Profitability remains unavailable pending approved financial rules.</section></>;
}
