"use client";
import { useRef, useState } from "react";

export type DocumentRow = { id: string; file_name: string; content_type: string | null; byte_size: number | null; notes: string | null; created_at: string; workspace_id: string | null; client_id: string | null; provider_id: string | null; clinician_id: string | null };
const size = (bytes: number | null) => bytes == null ? "—" : bytes < 1_000_000 ? `${Math.ceil(bytes / 1_000)} KB` : `${(bytes / 1_000_000).toFixed(1)} MB`;

export function DocumentsLibrary({ companyId, initialDocuments, canUpload }: { companyId: string; initialDocuments: DocumentRow[]; canUpload: boolean }) {
  const [documents, setDocuments] = useState(initialDocuments); const [error, setError] = useState(""); const [uploading, setUploading] = useState(false); const input = useRef<HTMLInputElement>(null);
  const upload = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const file = input.current?.files?.[0]; if (!file) { setError("Choose a file to upload."); return; } setUploading(true); setError(""); const data = new FormData(); data.set("companyId", companyId); data.set("file", file); const notes = new FormData(event.currentTarget).get("notes"); if (typeof notes === "string") data.set("notes", notes); const response = await fetch("/api/documents/upload", { method: "POST", body: data }); const body = await response.json(); setUploading(false); if (!response.ok) { setError(body.error ?? "Document could not be uploaded."); return; } setDocuments((current) => [body, ...current]); event.currentTarget.reset(); };
  return <main className="shell"><div className="page-head"><div><h1>Documents</h1><p className="muted">Private document metadata and files remain within the selected company’s RLS scope.</p></div></div>{error && <p className="error" role="alert">{error}</p>}{canUpload && <form className="card form-grid" onSubmit={upload}><h2>Upload document</h2><label className="field">File<input ref={input} type="file" required /></label><label className="field">Notes<input name="notes" maxLength={5000} /></label><div className="actions"><button className="btn" disabled={uploading}>{uploading ? "Uploading…" : "Upload"}</button></div></form>}<section className="card"><h2>Authorized library</h2>{documents.length === 0 ? <p className="muted">No authorized documents have been uploaded.</p> : <div className="table-wrap"><table><thead><tr><th>File</th><th>Type</th><th>Size</th><th>Added</th><th>Notes</th><th>Access</th></tr></thead><tbody>{documents.map((document) => <tr key={document.id}><td>{document.file_name}</td><td>{document.content_type ?? "—"}</td><td>{size(document.byte_size)}</td><td>{new Date(document.created_at).toLocaleString()}</td><td>{document.notes ?? "—"}</td><td><a href={`/api/documents/${document.id}/download?companyId=${companyId}`}>Download</a></td></tr>)}</tbody></table></div>}</section></main>;
}
