import { NextResponse } from "next/server";
import { logAuditEvent } from "@/lib/audit/log";
import { requireAutomationContext } from "@/lib/automation/auth";
import { userRest } from "@/lib/db/rest";
import { aiRequestSchema } from "@/lib/validation/automation";
import { isUuid, zodInputError } from "@/lib/validation/uuid";

export async function GET(request: Request) { const companyId = new URL(request.url).searchParams.get("companyId") ?? ""; try { await requireAutomationContext(companyId, "ai", "ai.read"); const rows = await userRest("GET", "ai_requests", { query: { select: "*", company_id: `eq.${companyId}`, order: "requested_at.desc", limit: "200" } }); return NextResponse.json(rows); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "AI queue unavailable." }, { status: 403 }); } }
export async function POST(request: Request) { const body = await request.json().catch(() => null) as { companyId?: string; data?: unknown } | null; const parsed = aiRequestSchema.safeParse(body?.data); if (!parsed.success) return NextResponse.json({ error: zodInputError(parsed.error) }, { status: 400 }); try { const { user, companyId } = await requireAutomationContext(body?.companyId ?? "", "ai", "ai.request"); const data = parsed.data; if (data.related_resource_id && data.related_resource_type) { const table = ({ client: "clients", provider: "providers", clinician: "clinicians", credential: "credentials", invoice: "invoice_financials", task: "tasks", activity: "activities" } as Record<string, string>)[data.related_resource_type]; const rows = await userRest<Array<{ id: string }>>("GET", table, { query: { select: "id", id: `eq.${data.related_resource_id}`, company_id: `eq.${companyId}`, archived_at: "is.null" } }); if (!rows[0]) return NextResponse.json({ error: "Related record must be authorized for the selected company." }, { status: 400 }); }
  const requestData = { workspace_id: data.workspace_id, request_type: data.request_type, related_resource_type: data.related_resource_type, related_resource_id: data.related_resource_id, communication_id: data.communication_id, template_id: data.template_id, input_context: { source: "manual" } }; const key = `manual:${user.id}:${data.request_type}:${data.related_resource_id ?? "none"}:${Date.now()}`; const rows = await userRest<Array<Record<string, unknown>>>("POST", "ai_requests", { body: { ...requestData, company_id: companyId, requested_by: user.id, execution_key: key, status: "queued" }, prefer: "return=representation" }); await logAuditEvent({ actorId: user.id, companyId, action: "ai.requested", resourceType: "ai_request", resourceId: typeof rows[0]?.id === "string" ? rows[0].id : undefined, after: { requestType: data.request_type, relatedType: data.related_resource_type, relatedId: data.related_resource_id } }); return NextResponse.json(rows[0], { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "AI request could not be queued." }, { status: 403 }); } }
export async function PATCH(request: Request) { const body = await request.json().catch(() => null) as { companyId?: string; id?: string; decision?: "approve" | "reject" } | null; if (!body?.id || !isUuid(body.id) || !body.decision) return NextResponse.json({ error: "AI request ID and review decision are required." }, { status: 400 }); try { const { user, companyId } = await requireAutomationContext(body.companyId ?? "", "ai", "ai.review"); const status = body.decision === "approve" ? "approved" : "rejected"; const rows = await userRest<Array<Record<string, unknown>>>("PATCH", "ai_requests", { query: { id: `eq.${body.id}`, company_id: `eq.${companyId}`, status: "eq.awaiting_review" }, body: { status, reviewed_by: user.id, reviewed_at: new Date().toISOString() }, prefer: "return=representation" }); if (!rows[0]) return NextResponse.json({ error: "Only an awaiting-review AI request can be reviewed." }, { status: 409 }); await logAuditEvent({ actorId: user.id, companyId, action: `ai.${status}`, resourceType: "ai_request", resourceId: body.id }); return NextResponse.json(rows[0]); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "AI request could not be reviewed." }, { status: 403 }); } }
