import { NextResponse } from "next/server";
import { logAuditEvent } from "@/lib/audit/log";
import { requireAutomationContext } from "@/lib/automation/auth";
import { userRest } from "@/lib/db/rest";
import { templateSchema } from "@/lib/validation/automation";
import { isUuid, zodInputError } from "@/lib/validation/uuid";

export async function GET(request: Request) { const companyId = new URL(request.url).searchParams.get("companyId") ?? ""; try { await requireAutomationContext(companyId, "automation", "templates.read"); return NextResponse.json(await userRest("GET", "templates", { query: { select: "*", company_id: `eq.${companyId}`, archived_at: "is.null", order: "name.asc,version.desc" } })); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Templates unavailable." }, { status: 403 }); } }
export async function POST(request: Request) { const body = await request.json().catch(() => null) as { companyId?: string; data?: unknown } | null; const parsed = templateSchema.safeParse(body?.data); if (!parsed.success) return NextResponse.json({ error: zodInputError(parsed.error) }, { status: 400 }); try { const { user, companyId } = await requireAutomationContext(body?.companyId ?? "", "automation", "templates.manage"); const rows = await userRest<Array<Record<string, unknown>>>("POST", "templates", { body: { ...parsed.data, company_id: companyId, created_by: user.id }, prefer: "return=representation" }); await logAuditEvent({ actorId: user.id, companyId, action: "template.created", resourceType: "template", resourceId: typeof rows[0]?.id === "string" ? rows[0].id : undefined, after: parsed.data }); return NextResponse.json(rows[0], { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Template could not be created." }, { status: 403 }); } }
export async function PATCH(request: Request) { const body = await request.json().catch(() => null) as { companyId?: string; id?: string; data?: unknown; archive?: boolean } | null; if (!body?.id || !isUuid(body.id)) return NextResponse.json({ error: "Template ID must be a valid UUID." }, { status: 400 }); const parsed = body.archive ? null : templateSchema.safeParse(body.data); if (parsed && !parsed.success) return NextResponse.json({ error: zodInputError(parsed.error) }, { status: 400 }); try { const { user, companyId } = await requireAutomationContext(body.companyId ?? "", "automation", "templates.manage"); const patch = body.archive ? { active: false, archived_at: new Date().toISOString() } : parsed!.data; const rows = await userRest<Array<Record<string, unknown>>>("PATCH", "templates", { query: { id: `eq.${body.id}`, company_id: `eq.${companyId}` }, body: patch, prefer: "return=representation" }); if (!rows[0]) return NextResponse.json({ error: "Template was not found." }, { status: 404 }); await logAuditEvent({ actorId: user.id, companyId, action: body.archive ? "template.archived" : "template.updated", resourceType: "template", resourceId: body.id, after: patch }); return NextResponse.json(rows[0]); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Template could not be updated." }, { status: 403 }); } }
