export type VaResource = "providers" | "clinicians" | "clients" | "credentials" | "billing" | "invoices" | "payments" | "payroll";
export const resourceSingular: Record<VaResource, string> = { providers: "Provider", clinicians: "Clinician", clients: "Client", credentials: "Credential", billing: "Billable record", invoices: "Invoice", payments: "Payment", payroll: "Pay period" };
export type ReferenceSource = "workspaces" | "clients" | "providers" | "clinicians" | "invoices";
export type Field = { key: string; label: string; type?: "text" | "email" | "tel" | "date" | "number" | "textarea"; required?: boolean; defaultValue?: string; reference?: ReferenceSource };
const workspace: Field = { key: "workspace_id", label: "Workspace", reference: "workspaces" };
const person = (roleLabel: string): Field[] => [{ key: "first_name", label: "First name", required: true }, { key: "middle_name", label: "Middle name" }, { key: "last_name", label: "Last name", required: true }, { key: "display_name", label: "Display name" }, { key: "email", label: "Email", type: "email" }, { key: "phone", label: "Phone", type: "tel" }, { key: "status", label: "Status", required: true, defaultValue: "active" }, { key: "type_or_role", label: roleLabel }, { key: "specialty", label: "Specialty" }, workspace, { key: "start_date", label: "Start date", type: "date" }, { key: "end_date", label: "End date", type: "date" }, { key: "notes", label: "Notes", type: "textarea" }];
export const vaFields: Record<VaResource, Field[]> = {
  providers: person("Provider type"), clinicians: person("Clinical role"),
  clients: [{ key: "name", label: "Client name", required: true }, { key: "status", label: "Status", required: true, defaultValue: "active" }, { key: "email", label: "Email", type: "email" }, { key: "phone", label: "Phone", type: "tel" }, { key: "address_line_1", label: "Address" }, { key: "city", label: "City" }, { key: "state_region", label: "State/region" }, { key: "postal_code", label: "Postal code" }, workspace, { key: "notes", label: "Notes", type: "textarea" }],
  credentials: [{ key: "credential_type", label: "Credential type", required: true }, { key: "provider_id", label: "Provider", reference: "providers" }, { key: "clinician_id", label: "Clinician", reference: "clinicians" }, { key: "credential_number", label: "Credential number" }, { key: "issuing_authority", label: "Issuing authority" }, { key: "issue_date", label: "Issue date", type: "date" }, { key: "expiration_date", label: "Expiration date", type: "date" }, { key: "status", label: "Status", required: true, defaultValue: "pending" }, { key: "renewal_status", label: "Renewal status" }, { key: "notes", label: "Notes", type: "textarea" }],
  billing: [{ key: "client_id", label: "Client", required: true, reference: "clients" }, { key: "provider_id", label: "Provider", reference: "providers" }, { key: "clinician_id", label: "Clinician", reference: "clinicians" }, { key: "invoice_id", label: "Invoice", reference: "invoices" }, workspace, { key: "service_date", label: "Service date", type: "date" }, { key: "description", label: "Description", required: true }, { key: "quantity", label: "Quantity", type: "number" }, { key: "unit_amount", label: "Unit amount", type: "number" }, { key: "status", label: "Billing status", required: true, defaultValue: "draft" }, { key: "notes", label: "Notes", type: "textarea" }],
  invoices: [{ key: "client_id", label: "Client", required: true, reference: "clients" }, workspace, { key: "invoice_number", label: "Invoice number", required: true }, { key: "billing_period_start", label: "Period start", type: "date" }, { key: "billing_period_end", label: "Period end", type: "date" }, { key: "issue_date", label: "Issue date", type: "date" }, { key: "due_date", label: "Due date", type: "date" }, { key: "adjustments", label: "Adjustments", type: "number", defaultValue: "0" }, { key: "notes", label: "Notes", type: "textarea" }],
  payments: [{ key: "client_id", label: "Client", required: true, reference: "clients" }, { key: "invoice_id", label: "Invoice", required: true, reference: "invoices" }, { key: "amount", label: "Amount", required: true, type: "number" }, { key: "payment_date", label: "Payment date", required: true, type: "date" }, { key: "payment_method", label: "Payment method" }, { key: "reference", label: "Reference" }, { key: "status", label: "Status", required: true, defaultValue: "pending" }, { key: "notes", label: "Notes", type: "textarea" }],
  payroll: [workspace, { key: "start_date", label: "Start date", required: true, type: "date" }, { key: "end_date", label: "End date", required: true, type: "date" }, { key: "notes", label: "Notes", type: "textarea" }],
};

export const labelFor = (key: string) => key.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
