"use client";
import { useEffect, useState } from "react";

type CalendarEvent = { id: string; title: string; description: string | null; starts_at: string; ends_at: string; all_day: boolean; status: "scheduled" | "cancelled" | "completed" };
type FormState = { title: string; description: string; starts_at: string; ends_at: string; status: CalendarEvent["status"] };
const toInput = (value: string) => new Date(value).toISOString().slice(0, 16);
const emptyForm = (): FormState => ({ title: "", description: "", starts_at: toInput(new Date().toISOString()), ends_at: toInput(new Date(Date.now() + 3_600_000).toISOString()), status: "scheduled" });

export function CalendarManager({ companyId, canCreate, canUpdate, canDelete }: { companyId: string; canCreate: boolean; canUpdate: boolean; canDelete: boolean }) {
  const [events, setEvents] = useState<CalendarEvent[]>([]); const [form, setForm] = useState<FormState | null>(null); const [editing, setEditing] = useState<CalendarEvent | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const requestEvents = async () => { const response = await fetch(`/api/calendar?companyId=${companyId}`); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not load calendar events."); return body as CalendarEvent[]; };
  const load = async () => setEvents(await requestEvents());
  useEffect(() => { let active = true; fetch(`/api/calendar?companyId=${companyId}`).then(async (response) => ({ response, body: await response.json() })).then(({ response, body }) => { if (!active) return; if (!response.ok) setError(body.error ?? "Could not load calendar events."); else setEvents(body); setLoading(false); }).catch(() => { if (active) { setError("Could not load calendar events."); setLoading(false); } }); return () => { active = false; }; }, [companyId]);
  const openEdit = (event: CalendarEvent) => { setEditing(event); setForm({ title: event.title, description: event.description ?? "", starts_at: toInput(event.starts_at), ends_at: toInput(event.ends_at), status: event.status }); setError(""); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!form) return; setError(""); const data = { ...form, starts_at: new Date(form.starts_at).toISOString(), ends_at: new Date(form.ends_at).toISOString(), all_day: false }; const response = await fetch("/api/calendar", { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(editing ? { companyId, id: editing.id, data } : { companyId, data }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Could not save calendar event."); return; } setForm(null); setEditing(null); await load().catch((reason) => setError(reason instanceof Error ? reason.message : "Could not refresh calendar events.")); };
  const remove = async (event: CalendarEvent) => { const confirmation = prompt(`Delete ${event.title} permanently? Participant rows will be removed with this event. Type DELETE to continue.`); if (confirmation !== "DELETE") return; const response = await fetch("/api/calendar", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyId, id: event.id, confirmation }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Could not delete calendar event."); return; } await load().catch((reason) => setError(reason instanceof Error ? reason.message : "Could not refresh calendar events.")); };
  return <main className="shell"><div className="page-head"><div><h1>Calendar</h1><p className="muted">Company-scoped operational events. No external calendar connections are enabled.</p></div>{canCreate && <button className="btn" onClick={() => { setEditing(null); setForm(emptyForm()); setError(""); }}>Create event</button>}</div>{error && <p className="error" role="alert">{error}</p>}{form && <form className="card form-grid" onSubmit={save}><h2>{editing ? "Edit event" : "Create event"}</h2><label className="field">Title<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label className="field">Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as CalendarEvent["status"] })}><option value="scheduled">Scheduled</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label className="field">Starts<input required type="datetime-local" value={form.starts_at} onChange={(event) => setForm({ ...form, starts_at: event.target.value })} /></label><label className="field">Ends<input required type="datetime-local" value={form.ends_at} onChange={(event) => setForm({ ...form, ends_at: event.target.value })} /></label><label className="field" style={{ gridColumn: "1 / -1" }}>Description<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><div className="actions"><button className="btn">Save event</button><button type="button" onClick={() => setForm(null)}>Cancel</button></div></form>}<section className="card">{loading ? <p>Loading…</p> : events.length === 0 ? <p className="muted">No authorized events yet.</p> : <div className="table-wrap"><table><thead><tr><th>When</th><th>Event</th><th>Status</th><th>Action</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td>{new Date(event.starts_at).toLocaleString()}<br /><span className="muted">to {new Date(event.ends_at).toLocaleString()}</span></td><td>{event.title}{event.description && <><br /><span className="muted">{event.description}</span></>}</td><td>{event.status}</td><td className="row-actions">{canUpdate && <button onClick={() => openEdit(event)}>Edit</button>}{canDelete && <button className="delete-action" onClick={() => remove(event)}>Delete</button>}{!canUpdate && !canDelete ? "—" : null}</td></tr>)}</tbody></table></div>}</section></main>;
}
