"use client";

import { useCallback, useEffect, useState } from "react";

type Option = { id: string; label: string };
type Request = Record<string, unknown> & { id: string };
const actions = [
  ["summarize_client", "Summarize this client", "clients"], ["summarize_activities", "Summarize recent activities", "clients"], ["draft_client_reply", "Draft a client reply", "clients"],
  ["summarize_provider", "Summarize this provider", "providers"], ["summarize_clinician", "Summarize this clinician", "clinicians"],
  ["draft_credential_reminder", "Draft credential reminder", "credentials"], ["draft_invoice_follow_up", "Draft invoice follow-up", "invoices"], ["generate_task_checklist", "Create suggested task checklist", "tasks"],
] as const;

export function AiAssistant({ companyId, canRequest, canReview }: { companyId: string; canRequest: boolean; canReview: boolean }) {
  const [options, setOptions] = useState<Record<string, Option[]>>({}); const [requests, setRequests] = useState<Request[]>([]); const [type, setType] = useState<string>("summarize_client"); const [relatedId, setRelatedId] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const [queue, optionResponse] = await Promise.all([fetch(`/api/ai?companyId=${companyId}`).then(async (response) => ({ response, body: await response.json() })), fetch(`/api/tasks/options?companyId=${companyId}`).then(async (response) => ({ response, body: await response.json() }))]); if (queue.response.ok) setRequests(queue.body); if (optionResponse.response.ok) setOptions(optionResponse.body); }, [companyId]);
  useEffect(() => { let active = true; const timer = setTimeout(() => { void load().catch(() => active && setError("Could not load AI Assistant.")); }, 0); return () => { active = false; clearTimeout(timer); }; }, [load]);
  const selected = actions.find((item) => item[0] === type) ?? actions[0]; const source = selected[2]; const relatedType = source === "clients" ? "client" : source === "providers" ? "provider" : source === "clinicians" ? "clinician" : source === "credentials" ? "credential" : source === "invoices" ? "invoice" : "task";
  const request = async () => { setError(""); setMessage(""); const response = await fetch("/api/ai", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyId, data: { request_type: type, related_resource_type: relatedId ? relatedType : undefined, related_resource_id: relatedId || undefined, input_context: {} } }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Could not queue AI request."); return; } setMessage("AI request queued for server-side processing and human review."); await load(); };
  const review = async (item: Request, decision: "approve" | "reject") => { const response = await fetch("/api/ai", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyId, id: item.id, decision }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Could not review AI request."); return; } setMessage(`AI draft ${decision}d.`); await load(); };
  return <main className="shell"><div className="page-head"><div><h1>AI Assistant</h1><p className="muted">Provider-agnostic drafts and summaries. AI cannot perform arbitrary Nexus writes, and external communications still require human approval.</p></div></div>{error && <p className="error">{error}</p>}{message && <p className="success">{message}</p>}<section className="card ai-composer"><h2>Request an AI draft</h2><label className="field">Action<select value={type} onChange={(event) => { setType(event.target.value); setRelatedId(""); }}>{actions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="field">Related record<select value={relatedId} onChange={(event) => setRelatedId(event.target.value)}><option value="">No related record</option>{(options[source] ?? []).map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label>{canRequest ? <button className="btn" onClick={request}>Queue AI request</button> : <p className="muted">You do not have AI request permission.</p>}<p className="muted">AI provider: Not Configured unless server-only provider settings are supplied. No content is sent from the browser.</p></section><section className="card table-wrap"><h2>AI work queue</h2><table><thead><tr><th>Request</th><th>Status</th><th>Requested</th><th>Draft / error</th><th>Review</th></tr></thead><tbody>{requests.map((item) => <tr key={item.id}><td>{String(item.request_type ?? "—").replaceAll("_", " ")}</td><td>{String(item.status ?? "—").replaceAll("_", " ")}</td><td>{item.requested_at ? new Date(String(item.requested_at)).toLocaleString() : "—"}</td><td>{typeof (item.response as Record<string, unknown> | null)?.content === "string" ? String((item.response as Record<string, unknown>).content).slice(0, 500) : String(item.error_details ?? "—")}</td><td className="row-actions">{canReview && item.status === "awaiting_review" && <><button onClick={() => review(item, "approve")}>Approve</button><button className="delete-action" onClick={() => review(item, "reject")}>Reject</button></>}</td></tr>)}</tbody></table>{!requests.length && <p className="muted">No AI requests yet.</p>}</section></main>;
}
