"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { actionTypes, aiRequestTypes, conditionOperators, triggerTypes } from "@/lib/validation/automation";

type Row = Record<string, unknown> & { id: string };
type Condition = { field: string; operator: string; value?: string };
type Action = { position: number; action_type: string; configuration: Record<string, unknown> };
type RuleForm = { workspace_id: string; name: string; description: string; active: boolean; trigger_type: string; conditions: Condition[]; actions: Action[] };
type TemplateForm = { name: string; category: string; subject: string; body: string; active: boolean };
type Options = { workspaces: Array<{ id: string; label: string }>; assignees: Array<{ id: string; label: string }> };

const triggerResource: Record<string, string> = {
  client_created: "client", client_status_changed: "client", task_created: "task", task_due_soon: "task", task_overdue: "task", task_completed: "task", task_status_changed: "task", credential_expiring: "credential", credential_expired: "credential", invoice_created: "invoice", invoice_due_soon: "invoice", invoice_overdue: "invoice", payment_posted: "payment", calendar_event_upcoming: "calendar_event", communication_approval_required: "communication",
};
const taskStatuses = ["not_started", "working", "waiting", "blocked", "done"];
const templateCategories = ["email", "client_reply", "onboarding", "credential_reminder", "invoice_reminder", "task_template", "internal_note", "ai_prompt", "pandadoc_preparation"];
const emptyRule = (): RuleForm => ({
  workspace_id: "", name: "", description: "", active: false, trigger_type: "credential_expiring",
  conditions: [{ field: "expiration_date", operator: "within_days", value: "30" }],
  actions: [
    { position: 1, action_type: "create_task", configuration: { title: "Renew {{credential.type}}", priority: "high", due_in_days: 7 } },
    { position: 2, action_type: "create_notification", configuration: { title: "Credential renewal needed", notification_type: "credential_expiring" } },
  ],
});
const emptyTemplate = (): TemplateForm => ({ name: "", category: "email", subject: "", body: "", active: true });
const text = (value: unknown) => typeof value === "string" ? value : "";
const record = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const dateTime = (value: unknown) => value ? new Date(String(value)).toLocaleString() : "—";
const statusLabel = (value: unknown) => text(value).replaceAll("_", " ");

function RuleEditor({ value, onChange, options, templates }: { value: RuleForm; onChange: (next: RuleForm) => void; options: Options; templates: Row[] }) {
  const updateAction = (index: number, update: Partial<Action>) => onChange({ ...value, actions: value.actions.map((action, itemIndex) => itemIndex === index ? { ...action, ...update } : action) });
  const updateConfig = (index: number, key: string, configValue: string | number) => updateAction(index, { configuration: { ...value.actions[index].configuration, [key]: configValue } });
  const addAction = () => onChange({ ...value, actions: [...value.actions, { position: value.actions.length + 1, action_type: "create_notification", configuration: { title: "Automation notification" } }] });
  return <div className="automation-editor">
    <label className="field">Rule name<input required value={value.name} onChange={(event) => onChange({ ...value, name: event.target.value })}/></label>
    <label className="field">Workspace scope<select value={value.workspace_id} onChange={(event) => onChange({ ...value, workspace_id: event.target.value })}><option value="">All authorized workspaces</option>{options.workspaces.map((workspace) => <option key={workspace.id} value={workspace.id}>{workspace.label}</option>)}</select></label>
    <label className="field">Trigger<select value={value.trigger_type} onChange={(event) => onChange({ ...value, trigger_type: event.target.value })}>{triggerTypes.map((trigger) => <option key={trigger} value={trigger}>{trigger.replaceAll("_", " ")}</option>)}</select></label>
    <label className="field">Description<input value={value.description} onChange={(event) => onChange({ ...value, description: event.target.value })}/></label>
    <label className="automation-check"><input type="checkbox" checked={value.active} onChange={(event) => onChange({ ...value, active: event.target.checked })}/> Enable rule</label>
    <section className="automation-subsection">
      <div className="section-inline"><h3>Conditions</h3><button type="button" onClick={() => onChange({ ...value, conditions: [...value.conditions, { field: "status", operator: "equals", value: "" }] })}>Add condition</button></div>
      {value.conditions.map((condition, index) => <div className="condition-row" key={`${condition.field}-${index}`}>
        <input aria-label="Condition field" value={condition.field} placeholder="Field" onChange={(event) => onChange({ ...value, conditions: value.conditions.map((item, itemIndex) => itemIndex === index ? { ...item, field: event.target.value } : item) })}/>
        <select aria-label="Condition operator" value={condition.operator} onChange={(event) => onChange({ ...value, conditions: value.conditions.map((item, itemIndex) => itemIndex === index ? { ...item, operator: event.target.value } : item) })}>{conditionOperators.map((operator) => <option key={operator} value={operator}>{operator.replaceAll("_", " ")}</option>)}</select>
        {!['is_empty', 'is_not_empty'].includes(condition.operator) && <input aria-label="Condition value" value={condition.value ?? ""} placeholder="Value" onChange={(event) => onChange({ ...value, conditions: value.conditions.map((item, itemIndex) => itemIndex === index ? { ...item, value: event.target.value } : item) })}/>} 
        <button type="button" className="delete-action" onClick={() => onChange({ ...value, conditions: value.conditions.filter((_, itemIndex) => itemIndex !== index) })}>Remove</button>
      </div>)}
    </section>
    <section className="automation-subsection">
      <div className="section-inline"><h3>Actions</h3><button type="button" onClick={addAction}>Add action</button></div>
      {value.actions.map((action, index) => <div className="action-editor" key={`${action.position}-${index}`}>
        <div className="section-inline"><strong>Action {index + 1}</strong><button type="button" className="delete-action" onClick={() => onChange({ ...value, actions: value.actions.filter((_, itemIndex) => itemIndex !== index).map((item, itemIndex) => ({ ...item, position: itemIndex + 1 })) })}>Remove</button></div>
        <select aria-label={`Action ${index + 1} type`} value={action.action_type} onChange={(event) => updateAction(index, { action_type: event.target.value, configuration: {} })}>{actionTypes.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select>
        {action.action_type === "create_task" && <><input aria-label="Task title" value={text(action.configuration.title)} placeholder="Task title, e.g. Renew {{credential.type}}" onChange={(event) => updateConfig(index, "title", event.target.value)}/><select aria-label="Task priority" value={text(action.configuration.priority) || "medium"} onChange={(event) => updateConfig(index, "priority", event.target.value)}>{["low", "medium", "high", "critical"].map((priority) => <option key={priority} value={priority}>{priority}</option>)}</select><input aria-label="Task due in days" type="number" min="0" max="365" value={Number(action.configuration.due_in_days ?? 0)} onChange={(event) => updateConfig(index, "due_in_days", Number(event.target.value))}/></>}
        {action.action_type === "create_notification" && <><input aria-label="Notification title" value={text(action.configuration.title)} placeholder="Notification title" onChange={(event) => updateConfig(index, "title", event.target.value)}/><input aria-label="Notification body" value={text(action.configuration.body)} placeholder="Optional notification body" onChange={(event) => updateConfig(index, "body", event.target.value)}/><select aria-label="Notification recipient" value={text(action.configuration.recipient_user_id)} onChange={(event) => updateConfig(index, "recipient_user_id", event.target.value)}><option value="">Rule owner</option>{options.assignees.map((assignee) => <option key={assignee.id} value={assignee.id}>{assignee.label}</option>)}</select><select aria-label="Notification recipient source" value={text(action.configuration.recipient_source)} onChange={(event) => updateConfig(index, "recipient_source", event.target.value)}><option value="">Use selected recipient</option><option value="task_assignee">Task assignee</option></select></>}
        {action.action_type === "prepare_communication" && <><select aria-label="Recipient source" value={text(action.configuration.recipient_source)} onChange={(event) => updateConfig(index, "recipient_source", event.target.value)}><option value="">Use recipient email below</option><option value="client_primary_contact">Client primary contact</option><option value="related_provider_email">Related provider email</option><option value="related_clinician_email">Related clinician email</option><option value="credential_holder_email">Credential holder email</option></select><input aria-label="Recipient" value={text(action.configuration.recipient)} placeholder="Recipient email when no source is selected" onChange={(event) => updateConfig(index, "recipient", event.target.value)}/><input aria-label="Subject" value={text(action.configuration.subject)} placeholder="Subject" onChange={(event) => updateConfig(index, "subject", event.target.value)}/><textarea aria-label="Communication body" value={text(action.configuration.body)} placeholder="Draft body; safe placeholders are supported" onChange={(event) => updateConfig(index, "body", event.target.value)}/></>}
        {action.action_type === "assign_task" && <select aria-label="Task assignee" value={text(action.configuration.assignee_id)} onChange={(event) => updateConfig(index, "assignee_id", event.target.value)}><option value="">Select an authorized assignee</option>{options.assignees.map((assignee) => <option key={assignee.id} value={assignee.id}>{assignee.label}</option>)}</select>}
        {action.action_type === "apply_approved_template" && <><select aria-label="Approved template" value={text(action.configuration.template_id)} onChange={(event) => updateConfig(index, "template_id", event.target.value)}><option value="">Select an active template</option>{templates.filter((template) => template.active === true).map((template) => <option key={template.id} value={template.id}>{text(template.name)}</option>)}</select><select aria-label="Template recipient source" value={text(action.configuration.recipient_source)} onChange={(event) => updateConfig(index, "recipient_source", event.target.value)}><option value="">Use recipient email below</option><option value="client_primary_contact">Client primary contact</option><option value="related_provider_email">Related provider email</option><option value="related_clinician_email">Related clinician email</option><option value="credential_holder_email">Credential holder email</option></select><input aria-label="Template recipient" value={text(action.configuration.recipient)} placeholder="Recipient email" onChange={(event) => updateConfig(index, "recipient", event.target.value)}/></>}
        {action.action_type === "queue_ai_draft" && <select aria-label="AI request type" value={text(action.configuration.request_type) || "draft_client_reply"} onChange={(event) => updateConfig(index, "request_type", event.target.value)}>{aiRequestTypes.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select>}
        {(["update_task_status", "update_record_status"].includes(action.action_type)) && <select aria-label="New task status" value={text(action.configuration.status) || "working"} onChange={(event) => updateConfig(index, "status", event.target.value)}>{taskStatuses.map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select>}
        {action.action_type === "queue_integration_event" && <><select aria-label="Integration" value={text(action.configuration.integration) || "webhook"} onChange={(event) => updateConfig(index, "integration", event.target.value)}>{["webhook", "zapier"].map((integration) => <option key={integration} value={integration}>{integration}</option>)}</select><input aria-label="Integration event type" value={text(action.configuration.event_type)} placeholder="Optional event type" onChange={(event) => updateConfig(index, "event_type", event.target.value)}/></>}
      </div>)}
    </section>
  </div>;
}

export function AutomationCenter({ companyId, canManage, canReview, initialTab = "rules" }: { companyId: string; canManage: boolean; canReview: boolean; canRequestAi: boolean; initialTab?: string }) {
  const [tab, setTab] = useState(initialTab); const [rules, setRules] = useState<Row[]>([]); const [runs, setRuns] = useState<Row[]>([]); const [actions, setActions] = useState<Row[]>([]); const [templates, setTemplates] = useState<Row[]>([]); const [ai, setAi] = useState<Row[]>([]); const [communications, setCommunications] = useState<Row[]>([]); const [integrations, setIntegrations] = useState<Row[]>([]); const [options, setOptions] = useState<Options>({ workspaces: [], assignees: [] }); const [form, setForm] = useState<RuleForm | null>(null); const [editing, setEditing] = useState<Row | null>(null); const [templateForm, setTemplateForm] = useState<TemplateForm | null>(null); const [templateEditing, setTemplateEditing] = useState<Row | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => {
    const results = await Promise.all(["automation", "templates", "ai", "communications"].map(async (resource) => { const response = await fetch(`/api/${resource}?companyId=${companyId}`); return { resource, response, body: await response.json() as unknown }; }));
    const automation = results.find((result) => result.resource === "automation"); if (!automation?.response.ok) throw new Error(record(automation?.body).error as string || "Could not load Automation Center.");
    const body = record(automation.body); setRules(Array.isArray(body.rules) ? body.rules as Row[] : []); setRuns(Array.isArray(body.runs) ? body.runs as Row[] : []); setActions(Array.isArray(body.actions) ? body.actions as Row[] : []); setIntegrations(Array.isArray(body.integrations) ? body.integrations as Row[] : []);
    for (const result of results.filter((item) => item.resource !== "automation" && item.response.ok)) { if (result.resource === "templates") setTemplates(Array.isArray(result.body) ? result.body as Row[] : []); if (result.resource === "ai") setAi(Array.isArray(result.body) ? result.body as Row[] : []); if (result.resource === "communications") setCommunications(Array.isArray(result.body) ? result.body as Row[] : []); }
    const optionResponse = await fetch(`/api/tasks/options?companyId=${companyId}`); if (optionResponse.ok) { const optionBody = await optionResponse.json() as Record<string, unknown>; setOptions({ workspaces: Array.isArray(optionBody.workspaces) ? optionBody.workspaces as Options["workspaces"] : [], assignees: Array.isArray(optionBody.assignees) ? optionBody.assignees as Options["assignees"] : [] }); }
  }, [companyId]);
  useEffect(() => { let active = true; const timer = setTimeout(() => { void load().catch((reason) => active && setError(reason instanceof Error ? reason.message : "Could not load Automation Center.")).finally(() => active && setLoading(false)); }, 0); return () => { active = false; clearTimeout(timer); }; }, [load]);
  const byRule = useMemo(() => new Map(rules.map((rule) => [rule.id, rule])), [rules]);
  const actionsFor = (ruleId: string) => actions.filter((action) => action.automation_rule_id === ruleId).sort((a, b) => Number(a.position) - Number(b.position));
  const notify = async (promise: Promise<Response>, success: string) => { setError(""); setMessage(""); const response = await promise; const result = await response.json() as Record<string, unknown>; if (!response.ok) { setError(text(result.error) || "Request failed."); return; } setMessage(success); await load(); };
  const saveRule = async (event: React.FormEvent) => { event.preventDefault(); if (!form) return; const data = { ...form, workspace_id: form.workspace_id || undefined, trigger_resource: triggerResource[form.trigger_type], conditions: form.conditions.filter((condition) => condition.field) }; await notify(fetch("/api/automation", { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(editing ? { companyId, id: editing.id, data } : { companyId, data }) }), editing ? "Automation rule updated." : "Automation rule created."); setForm(null); setEditing(null); };
  const saveTemplate = async (event: React.FormEvent) => { event.preventDefault(); if (!templateForm) return; await notify(fetch("/api/templates", { method: templateEditing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(templateEditing ? { companyId, id: templateEditing.id, data: templateForm } : { companyId, data: templateForm }) }), templateEditing ? "Template updated." : "Template created."); setTemplateForm(null); setTemplateEditing(null); };
  const openEdit = (rule: Row) => { setEditing(rule); setForm({ workspace_id: text(rule.workspace_id), name: text(rule.name), description: text(rule.description), active: rule.active === true, trigger_type: text(rule.trigger_type), conditions: Array.isArray(rule.conditions) ? rule.conditions as Condition[] : [], actions: actionsFor(rule.id).map((action) => ({ position: Number(action.position), action_type: text(action.action_type), configuration: record(action.configuration) })) }); };
  const toggleRule = (rule: Row) => { const data = { workspace_id: text(rule.workspace_id), name: text(rule.name), description: text(rule.description), active: rule.active !== true, trigger_type: text(rule.trigger_type), trigger_resource: text(rule.trigger_resource), conditions: Array.isArray(rule.conditions) ? rule.conditions as Condition[] : [], actions: actionsFor(rule.id).map((action) => ({ position: Number(action.position), action_type: text(action.action_type), configuration: record(action.configuration) })) }; return notify(fetch("/api/automation", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyId, id: rule.id, data }) }), rule.active === true ? "Rule disabled." : "Rule enabled."); };
  const reviewCommunication = async (communication: Row, action: "save" | "approve" | "queue" | "cancel") => { const finalBody = prompt("Review/edit the communication body:", text(communication.final_body) || text(communication.draft_body)); if (finalBody == null) return; await notify(fetch("/api/communications", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyId, data: { id: communication.id, final_body: finalBody, subject: text(communication.subject), action } }) }), `Communication ${action}d.`); };
  const tabs = ["rules", "runs", "templates", "ai", "communications", "integrations", "health"];
  return <main className="shell automation-shell">
    <div className="page-head"><div><h1>Automation Center</h1><p className="muted">Tenant-scoped rules, durable run history, human-approved communications, and provider-neutral queues.</p></div>{canManage && <button className="btn" onClick={() => { setEditing(null); setForm(emptyRule()); }}>Create rule</button>}</div>
    <div className="automation-tabs">{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item.replaceAll("_", " ")}</button>)}</div>{error && <p role="alert" className="error">{error}</p>}{message && <p className="success">{message}</p>}
    {form && <form className="card" onSubmit={saveRule}><div className="section-inline"><h2>{editing ? "Edit automation rule" : "Create automation rule"}</h2><button type="button" onClick={() => { setForm(null); setEditing(null); }}>Cancel</button></div><RuleEditor value={form} onChange={setForm} options={options} templates={templates}/><div className="actions"><button className="btn">Save rule</button></div></form>}
    {tab === "rules" && <section className="card table-wrap">{loading ? <p>Loading…</p> : rules.length === 0 ? <p className="muted">No automation rules yet. Disabled examples appear after the migration is applied.</p> : <table><thead><tr><th>Rule</th><th>Trigger</th><th>State</th><th>Last run</th><th>Actions</th></tr></thead><tbody>{rules.map((rule) => <tr key={rule.id}><td><strong>{text(rule.name)}</strong><div className="muted">{text(rule.description)}</div><small>{actionsFor(rule.id).map((action) => statusLabel(action.action_type)).join(" · ")}</small></td><td>{statusLabel(rule.trigger_type)}</td><td>{rule.active === true ? "Enabled" : "Disabled"}</td><td>{dateTime(rule.last_run_at)}</td><td className="row-actions">{canManage && <><button onClick={() => openEdit(rule)}>Edit</button><button onClick={() => void toggleRule(rule)}>{rule.active === true ? "Disable" : "Enable"}</button></>}</td></tr>)}</tbody></table>}</section>}
    {tab === "runs" && <section className="card table-wrap"><table><thead><tr><th>Rule</th><th>Trigger</th><th>Related record</th><th>Started</th><th>Finished</th><th>Status</th><th>Actions</th><th>Failure / retry</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td>{text(byRule.get(text(run.automation_rule_id))?.name) || "Archived rule"}</td><td>{statusLabel(run.trigger_type)}</td><td>{statusLabel(run.related_resource_type)} {text(run.related_resource_id).slice(0, 8)}</td><td>{dateTime(run.started_at || run.created_at)}</td><td>{dateTime(run.finished_at)}</td><td>{statusLabel(run.status)}</td><td>{String(run.actions_succeeded ?? 0)}/{String(run.actions_attempted ?? 0)} succeeded; {String(run.actions_failed ?? 0)} failed</td><td>{text(run.error_details) || `Retries: ${String(run.retry_count ?? 0)}`}</td></tr>)}</tbody></table>{!runs.length && <p className="muted">No automation runs yet.</p>}</section>}
    {tab === "templates" && <><div className="page-head compact"><h2>Template library</h2>{canManage && <button className="btn" onClick={() => { setTemplateEditing(null); setTemplateForm(emptyTemplate()); }}>Create template</button>}</div>{templateForm && <form className="card form-grid" onSubmit={saveTemplate}><h2>{templateEditing ? "Edit template" : "Create template"}</h2><label className="field">Name<input required value={templateForm.name} onChange={(event) => setTemplateForm({ ...templateForm, name: event.target.value })}/></label><label className="field">Category<select value={templateForm.category} onChange={(event) => setTemplateForm({ ...templateForm, category: event.target.value })}>{templateCategories.map((category) => <option key={category} value={category}>{category.replaceAll("_", " ")}</option>)}</select></label><label className="field form-wide">Subject<input value={templateForm.subject} onChange={(event) => setTemplateForm({ ...templateForm, subject: event.target.value })}/></label><label className="field form-wide">Body<textarea required value={templateForm.body} onChange={(event) => setTemplateForm({ ...templateForm, body: event.target.value })}/></label><label className="automation-check"><input type="checkbox" checked={templateForm.active} onChange={(event) => setTemplateForm({ ...templateForm, active: event.target.checked })}/> Active</label><div className="actions"><button className="btn">Save template</button><button type="button" onClick={() => setTemplateForm(null)}>Cancel</button></div></form>}<section className="card table-wrap"><table><thead><tr><th>Name</th><th>Category</th><th>Version</th><th>State</th><th>Actions</th></tr></thead><tbody>{templates.map((template) => <tr key={template.id}><td><strong>{text(template.name)}</strong><div className="muted">{text(template.subject)}</div></td><td>{statusLabel(template.category)}</td><td>{String(template.version ?? 1)}</td><td>{template.active === true ? "Active" : "Inactive"}</td><td className="row-actions">{canManage && <button onClick={() => { setTemplateEditing(template); setTemplateForm({ name: text(template.name), category: text(template.category), subject: text(template.subject), body: text(template.body), active: template.active === true }); }}>Edit</button>}</td></tr>)}</tbody></table>{!templates.length && <p className="muted">No templates available.</p>}</section></>}
    {tab === "ai" && <QueueTable title="AI queue" rows={ai} columns={["request_type", "status", "requested_at", "error_details"]}/>} 
    {tab === "communications" && <section className="card table-wrap"><table><thead><tr><th>Recipient</th><th>Subject</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{communications.map((communication) => <tr key={communication.id}><td>{text(communication.recipient)}</td><td>{text(communication.subject)}</td><td>{statusLabel(communication.status)}</td><td>{dateTime(communication.created_at)}</td><td className="row-actions">{canReview && ["draft", "ai_draft_requested", "awaiting_review", "approved"].includes(text(communication.status)) && <><button onClick={() => void reviewCommunication(communication, "save")}>Review/Edit</button>{communication.status === "approved" ? <button onClick={() => void reviewCommunication(communication, "queue")}>Queue send</button> : <button onClick={() => void reviewCommunication(communication, "approve")}>Approve</button>}<button className="delete-action" onClick={() => void reviewCommunication(communication, "cancel")}>Cancel</button></>}</td></tr>)}</tbody></table>{!communications.length && <p className="muted">No communications queued for review.</p>}</section>}
    {tab === "integrations" && <><QueueTable title="Integration queue" rows={integrations} columns={["integration", "direction", "event_type", "status", "retry_count", "error_details", "created_at"]}/><section className="card"><h2>Adapter status</h2><p className="muted">Email, PandaDoc, Zapier/webhooks remain Not Configured until their server-only environment variables and provider adapters are configured. No external success is fabricated.</p><ul><li>Email: sends only approved communications</li><li>PandaDoc: adapter boundary ready; no document is fabricated</li><li>Zapier / webhooks: signed inbound and outbound events are persisted with retry status</li></ul></section></>}
    {tab === "health" && <section className="card"><h2>Automation health</h2><div className="detail-grid"><div><strong>Active rules</strong><p>{rules.filter((rule) => rule.active === true).length}</p></div><div><strong>Failed runs</strong><p>{runs.filter((run) => ["failed", "partially_failed"].includes(text(run.status))).length}</p></div><div><strong>AI awaiting review</strong><p>{ai.filter((request) => request.status === "awaiting_review").length}</p></div><div><strong>Communications awaiting approval</strong><p>{communications.filter((communication) => ["draft", "ai_draft_requested", "awaiting_review"].includes(text(communication.status))).length}</p></div><div><strong>Failed integrations</strong><p>{integrations.filter((event) => event.status === "failed").length}</p></div></div><p className="muted">Schedule the protected worker endpoint after configuring <code>AUTOMATION_WORKER_TOKEN</code>; this UI does not impersonate a background worker.</p></section>}
  </main>;
}

function QueueTable({ title, rows, columns }: { title: string; rows: Row[]; columns: string[] }) {
  return <section className="card table-wrap"><h2>{title}</h2><table><thead><tr>{columns.map((column) => <th key={column}>{column.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}>{columns.map((column) => <td key={column}>{column.includes("at") ? dateTime(row[column]) : statusLabel(row[column])}</td>)}</tr>)}</tbody></table>{!rows.length && <p className="muted">No entries in this queue.</p>}</section>;
}
