"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { type Field, type ReferenceSource, type VaResource, vaFields } from "@/lib/va/presentation";
import { displayNameFor } from "@/lib/va/display";

type Row = Record<string, unknown> & { id: string; created_at?: string; status?: string };
type ReferenceOption = { id: string; label: string };
const emptyFor = (fields: Field[]) => Object.fromEntries(fields.map((field) => [field.key, field.defaultValue ?? ""]));
const toInput = (value: unknown, type?: Field["type"]) => value == null ? "" : type === "date" ? String(value).slice(0, 10) : String(value);

export function OperationalResource({ resource, title, companyId, companySlug, canCreate, canUpdate, canArchive, canDelete }: { resource: VaResource; title: string; companyId: string; companySlug: string; canCreate: boolean; canUpdate: boolean; canArchive: boolean; canDelete: boolean }) {
  const searchParams = useSearchParams(); const fields = vaFields[resource]; const [rows, setRows] = useState<Row[]>([]); const [references, setReferences] = useState<Partial<Record<ReferenceSource, ReferenceOption[]>>>({}); const [query, setQuery] = useState(""); const [status, setStatus] = useState(searchParams.get("status") ?? ""); const [form, setForm] = useState<Record<string, string> | null>(null); const [editing, setEditing] = useState<Row | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { const response = await fetch(`/api/va/${resource}?companyId=${companyId}`); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not load records."); return body as Row[]; };
  useEffect(() => { let active = true; fetch(`/api/va/${resource}?companyId=${companyId}`).then(async (response) => ({ response, body: await response.json() })).then(({ response, body }) => { if (!active) return; if (!response.ok) setError(body.error ?? "Could not load records."); else setRows(body); setLoading(false); }).catch(() => { if (active) { setError("Could not load records."); setLoading(false); } }); return () => { active = false; }; }, [companyId, resource]);
  useEffect(() => { let active = true; fetch(`/api/va/references?companyId=${companyId}&resource=${resource}`).then(async (response) => ({ response, body: await response.json() })).then(({ response, body }) => { if (active && response.ok) setReferences(body); }).catch(() => undefined); return () => { active = false; }; }, [companyId, resource]);
  const visible = useMemo(() => rows.filter((row) => { const text = Object.values(row).join(" ").toLowerCase(); const health = searchParams.get("health"); const expiration = row.expiration_date ? Date.parse(`${String(row.expiration_date).slice(0, 10)}T00:00:00Z`) : Number.NaN; const today = Date.UTC(new Date().getUTCFullYear(), new Date().getUTCMonth(), new Date().getUTCDate()); const days = Number.isNaN(expiration) ? null : Math.floor((expiration - today) / 86_400_000); const healthMatches = resource !== "credentials" || !health || health === "30" && days !== null && days >= 0 && days <= 30 || health === "31_60" && days !== null && days >= 31 && days <= 60 || health === "61_90" && days !== null && days >= 61 && days <= 90 || health === "expired" && days !== null && days < 0; return text.includes(query.toLowerCase()) && (!status || row.status === status) && healthMatches; }).sort((a, b) => String(a.created_at ?? "").localeCompare(String(b.created_at ?? "")) * -1), [resource, rows, query, searchParams, status]);
  const openCreate = () => { setEditing(null); setForm(emptyFor(fields)); setError(""); };
  const openEdit = (row: Row) => { setEditing(row); const values = Object.fromEntries(fields.map((field) => [field.key, toInput(field.key === "type_or_role" ? row.provider_type ?? row.role : row[field.key], field.type)])); setForm(values); setError(""); };
  const refresh = async () => { try { setRows(await load()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load records."); } };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!form) return; setError(""); const response = await fetch(`/api/va/${resource}`, { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(editing ? { companyId, id: editing.id, data: form } : { companyId, data: form }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Could not save record."); return; } setForm(null); setEditing(null); await refresh(); };
  const archive = async (row: Row) => { if (!confirm(`Archive this ${title.slice(0, -1).toLowerCase()}?`)) return; const response = await fetch(`/api/va/${resource}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyId, id: row.id, archive: true }) }); if (!response.ok) { const body = await response.json(); setError(body.error ?? "Could not archive record."); return; } await refresh(); };
  const remove = async (row: Row) => { const confirmation = prompt(`Delete Permanently removes ${displayNameFor(resource, row)} forever. Archive is reversible. Type DELETE to continue.`); if (confirmation !== "DELETE") return; const response = await fetch(`/api/va/${resource}`, { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ companyId, id: row.id, confirmation }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Could not permanently delete record."); return; } await refresh(); };
  const statuses = [...new Set(rows.map((row) => row.status).filter((value): value is string => typeof value === "string"))];
  return <main className="shell"><div className="page-head"><div><h1>{title}</h1><p className="muted">Live Tidemark VA records. Access is enforced by permissions and database RLS.</p></div>{canCreate && <button className="btn" onClick={openCreate}>Add {title.slice(0, -1)}</button>}</div>{error && <p role="alert" className="error">{error}</p>}{form && <form className="card form-grid" onSubmit={submit}><h2>{editing ? `Edit ${title.slice(0, -1)}` : `Add ${title.slice(0, -1)}`}</h2>{fields.map((field) => <label className="field" key={field.key}>{field.label}{field.reference ? <select required={field.required} value={form[field.key] ?? ""} onChange={(event) => setForm({ ...form, [field.key]: event.target.value })}><option value="">{field.required ? `Select ${field.label.toLowerCase()}` : `No ${field.label.toLowerCase()}`}</option>{(references[field.reference] ?? []).map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select> : field.type === "textarea" ? <textarea value={form[field.key] ?? ""} onChange={(event) => setForm({ ...form, [field.key]: event.target.value })}/> : <input required={field.required} type={field.type ?? "text"} step={field.type === "number" ? "0.01" : undefined} value={form[field.key] ?? ""} onChange={(event) => setForm({ ...form, [field.key]: event.target.value })}/>}</label>)}<div className="actions"><button className="btn">Save</button><button type="button" onClick={() => setForm(null)}>Cancel</button></div></form>}<section className="card"><div className="toolbar"><input aria-label={`Search ${title}`} placeholder={`Search ${title.toLowerCase()}`} value={query} onChange={(event) => setQuery(event.target.value)}/><select aria-label="Filter status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select><span className="muted">{visible.length} record(s)</span></div>{loading ? <p>Loading…</p> : visible.length === 0 ? <p className="muted">No {title.toLowerCase()} match this view. Create an authorized record to begin.</p> : <div className="table-wrap"><table><thead><tr><th>Name</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{visible.map((row) => <tr key={row.id}><td>{displayNameFor(resource, row)}</td><td>{String(row.status ?? "—")}</td><td>{row.created_at ? new Date(String(row.created_at)).toLocaleDateString() : "—"}</td><td className="row-actions"><Link href={`/c/${companySlug}/${resource}/${row.id}`}>View</Link>{canUpdate && <button onClick={() => openEdit(row)}>Edit</button>}{canArchive && <button onClick={() => archive(row)}>Archive</button>}{canDelete && <button className="delete-action" onClick={() => remove(row)}>Delete Permanently</button>}</td></tr>)}</tbody></table></div>}</section></main>;
}
